workflows:
  expo-build:
    name: Expo Android Build
    environment:
      node: 18.16.0
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build with EAS
        script: |
          eas build --platform android --non-interactive
    artifacts:
      - dist/**/*.apk
